apiVersion: validation.spectrocloud.labs/v1alpha1
kind: MaasValidator
metadata:
  name: maasvalidator-sample
spec:
  MaasInstance:
    host: "http://maas.sc:5240/MAAS"
    auth:
      # You have to specify credentials secret
      secretName: maas-credentials
  MaasInstanceRules:
    name: "rules for sc maas"
    bootable-images:
    - name: ubuntu/focal
      os-arch: amd64/ga-20.04
    nameservers:
    - "8.8.8.8"
    - "9.9.9.9"
